package com.ybtx.domain;
// Generated 2017-7-29 17:34:30 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private int companyId;
	private String companyName;
	private Set receives = new HashSet(0);
	private Set submits = new HashSet(0);

	public Company() {
	}

	public Company(int companyId, String companyName) {
		this.companyId = companyId;
		this.companyName = companyName;
	}

	public Company(int companyId, String companyName, Set receives, Set submits) {
		this.companyId = companyId;
		this.companyName = companyName;
		this.receives = receives;
		this.submits = submits;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public Set getReceives() {
		return this.receives;
	}

	public void setReceives(Set receives) {
		this.receives = receives;
	}

	public Set getSubmits() {
		return this.submits;
	}

	public void setSubmits(Set submits) {
		this.submits = submits;
	}

}
