package com.ybtx.domain;
// Generated 2017-7-28 23:24:18 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int employeeId;
	private Serializable employeeName;
	private Serializable employeePhone;
	private Serializable employeePicture;
	private Set uses = new HashSet(0);
	private Set makes = new HashSet(0);

	public Employee() {
	}

	public Employee(int employeeId, Serializable employeeName) {
		this.employeeId = employeeId;
		this.employeeName = employeeName;
	}

	public Employee(int employeeId, Serializable employeeName, Serializable employeePhone, Serializable employeePicture,
			Set uses, Set makes) {
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.employeePhone = employeePhone;
		this.employeePicture = employeePicture;
		this.uses = uses;
		this.makes = makes;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public Serializable getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(Serializable employeeName) {
		this.employeeName = employeeName;
	}

	public Serializable getEmployeePhone() {
		return this.employeePhone;
	}

	public void setEmployeePhone(Serializable employeePhone) {
		this.employeePhone = employeePhone;
	}

	public Serializable getEmployeePicture() {
		return this.employeePicture;
	}

	public void setEmployeePicture(Serializable employeePicture) {
		this.employeePicture = employeePicture;
	}

	public Set getUses() {
		return this.uses;
	}

	public void setUses(Set uses) {
		this.uses = uses;
	}

	public Set getMakes() {
		return this.makes;
	}

	public void setMakes(Set makes) {
		this.makes = makes;
	}

}
