package com.ybtx.domain;
// Generated 2017-7-29 17:34:30 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int employeeId;
	private String employeeName;
	private String employeePhone;
	private String employeePicture;
	private Set uses = new HashSet(0);
	private Set makes = new HashSet(0);
	private String usage;

	public String getUsage() {
		return usage;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

	public Employee() {
	}

	public Employee(int employeeId, String employeeName) {
		this.employeeId = employeeId;
		this.employeeName = employeeName;
	}

	public Employee(int employeeId, String employeeName, String employeePhone, String employeePicture, Set uses,
			Set makes) {
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.employeePhone = employeePhone;
		this.employeePicture = employeePicture;
		this.uses = uses;
		this.makes = makes;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getEmployeePhone() {
		return this.employeePhone;
	}

	public void setEmployeePhone(String employeePhone) {
		this.employeePhone = employeePhone;
	}

	public String getEmployeePicture() {
		return this.employeePicture;
	}

	public void setEmployeePicture(String employeePicture) {
		this.employeePicture = employeePicture;
	}

	public Set getUses() {
		return this.uses;
	}

	public void setUses(Set uses) {
		this.uses = uses;
	}

	public Set getMakes() {
		return this.makes;
	}

	public void setMakes(Set makes) {
		this.makes = makes;
	}

}
