package com.ybtx.domain;
// Generated 2017-7-29 17:34:30 by Hibernate Tools 3.4.0.CR1

/**
 * Make generated by hbm2java
 */
public class Make implements java.io.Serializable {

	private int makeId;
	private Employee employee;
	private Product product;
	private String makeDate;
	private Integer makeAmount;
	private Integer employeeId;
	private Integer productId;

	public Integer getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public Integer getProductId() {
		return productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Make() {
	}

	public Make(int makeId) {
		this.makeId = makeId;
	}

	public Make(int makeId, Employee employee, Product product, String makeDate, Integer makeAmount) {
		this.makeId = makeId;
		this.employee = employee;
		this.product = product;
		this.makeDate = makeDate;
		this.makeAmount = makeAmount;
	}

	public int getMakeId() {
		return this.makeId;
	}

	public void setMakeId(int makeId) {
		this.makeId = makeId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getMakeDate() {
		return this.makeDate;
	}

	public void setMakeDate(String makeDate) {
		this.makeDate = makeDate;
	}

	public Integer getMakeAmount() {
		return this.makeAmount;
	}

	public void setMakeAmount(Integer makeAmount) {
		this.makeAmount = makeAmount;
	}

}
