package com.ybtx.domain;
// Generated 2017-7-28 23:24:18 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Make generated by hbm2java
 */
public class Make implements java.io.Serializable {

	private int makeId;
	private Employee employee;
	private Product product;
	private Serializable makeDate;
	private Integer makeAmount;

	public Make() {
	}

	public Make(int makeId) {
		this.makeId = makeId;
	}

	public Make(int makeId, Employee employee, Product product, Serializable makeDate, Integer makeAmount) {
		this.makeId = makeId;
		this.employee = employee;
		this.product = product;
		this.makeDate = makeDate;
		this.makeAmount = makeAmount;
	}

	public int getMakeId() {
		return this.makeId;
	}

	public void setMakeId(int makeId) {
		this.makeId = makeId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Serializable getMakeDate() {
		return this.makeDate;
	}

	public void setMakeDate(Serializable makeDate) {
		this.makeDate = makeDate;
	}

	public Integer getMakeAmount() {
		return this.makeAmount;
	}

	public void setMakeAmount(Integer makeAmount) {
		this.makeAmount = makeAmount;
	}

}
