package com.ybtx.domain;
// Generated 2017-7-28 23:24:18 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int productId;
	private Serializable productName;
	private Serializable productType;
	private int productAmount;
	private Set materials = new HashSet(0);
	private Set makes = new HashSet(0);
	private Set submits = new HashSet(0);

	public Product() {
	}

	public Product(int productId, Serializable productName, Serializable productType, int productAmount) {
		this.productId = productId;
		this.productName = productName;
		this.productType = productType;
		this.productAmount = productAmount;
	}

	public Product(int productId, Serializable productName, Serializable productType, int productAmount, Set materials,
			Set makes, Set submits) {
		this.productId = productId;
		this.productName = productName;
		this.productType = productType;
		this.productAmount = productAmount;
		this.materials = materials;
		this.makes = makes;
		this.submits = submits;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Serializable getProductName() {
		return this.productName;
	}

	public void setProductName(Serializable productName) {
		this.productName = productName;
	}

	public Serializable getProductType() {
		return this.productType;
	}

	public void setProductType(Serializable productType) {
		this.productType = productType;
	}

	public int getProductAmount() {
		return this.productAmount;
	}

	public void setProductAmount(int productAmount) {
		this.productAmount = productAmount;
	}

	public Set getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set materials) {
		this.materials = materials;
	}

	public Set getMakes() {
		return this.makes;
	}

	public void setMakes(Set makes) {
		this.makes = makes;
	}

	public Set getSubmits() {
		return this.submits;
	}

	public void setSubmits(Set submits) {
		this.submits = submits;
	}

}
