package com.ybtx.domain;
// Generated 2017-7-29 17:34:30 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int productId;
	private String productName;
	private String productType;
	private int productAmount;
	private double productWage;
	private double productMargin;
	private Set materials = new HashSet(0);
	private Set makes = new HashSet(0);
	private Set submits = new HashSet(0);
	private String usage;

	public String getUsage() {
		return usage;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

	public Product() {
	}

	public Product(int productId, String productName, String productType, int productAmount, double productWage,
			double productMargin) {
		this.productId = productId;
		this.productName = productName;
		this.productType = productType;
		this.productAmount = productAmount;
		this.productWage = productWage;
		this.productMargin = productMargin;
	}

	public Product(int productId, String productName, String productType, int productAmount, double productWage,
			double productMargin, Set materials, Set makes, Set submits) {
		this.productId = productId;
		this.productName = productName;
		this.productType = productType;
		this.productAmount = productAmount;
		this.productWage = productWage;
		this.productMargin = productMargin;
		this.materials = materials;
		this.makes = makes;
		this.submits = submits;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductType() {
		return this.productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public int getProductAmount() {
		return this.productAmount;
	}

	public void setProductAmount(int productAmount) {
		this.productAmount = productAmount;
	}

	public double getProductWage() {
		return this.productWage;
	}

	public void setProductWage(double productWage) {
		this.productWage = productWage;
	}

	public double getProductMargin() {
		return this.productMargin;
	}

	public void setProductMargin(double productMargin) {
		this.productMargin = productMargin;
	}

	public Set getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set materials) {
		this.materials = materials;
	}

	public Set getMakes() {
		return this.makes;
	}

	public void setMakes(Set makes) {
		this.makes = makes;
	}

	public Set getSubmits() {
		return this.submits;
	}

	public void setSubmits(Set submits) {
		this.submits = submits;
	}

}
