package com.ybtx.domain;
// Generated 2017-7-28 23:24:18 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * ReceiveId generated by hbm2java
 */
public class ReceiveId implements java.io.Serializable {

	private Integer receiveId;
	private Integer receiveCompany;
	private Integer receiveMaterial;
	private Serializable receiveDate;
	private Integer receiveAmount;

	public ReceiveId() {
	}

	public ReceiveId(Integer receiveId, Integer receiveCompany, Integer receiveMaterial, Serializable receiveDate,
			Integer receiveAmount) {
		this.receiveId = receiveId;
		this.receiveCompany = receiveCompany;
		this.receiveMaterial = receiveMaterial;
		this.receiveDate = receiveDate;
		this.receiveAmount = receiveAmount;
	}

	public Integer getReceiveId() {
		return this.receiveId;
	}

	public void setReceiveId(Integer receiveId) {
		this.receiveId = receiveId;
	}

	public Integer getReceiveCompany() {
		return this.receiveCompany;
	}

	public void setReceiveCompany(Integer receiveCompany) {
		this.receiveCompany = receiveCompany;
	}

	public Integer getReceiveMaterial() {
		return this.receiveMaterial;
	}

	public void setReceiveMaterial(Integer receiveMaterial) {
		this.receiveMaterial = receiveMaterial;
	}

	public Serializable getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(Serializable receiveDate) {
		this.receiveDate = receiveDate;
	}

	public Integer getReceiveAmount() {
		return this.receiveAmount;
	}

	public void setReceiveAmount(Integer receiveAmount) {
		this.receiveAmount = receiveAmount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReceiveId))
			return false;
		ReceiveId castOther = (ReceiveId) other;

		return ((this.getReceiveId() == castOther.getReceiveId()) || (this.getReceiveId() != null
				&& castOther.getReceiveId() != null && this.getReceiveId().equals(castOther.getReceiveId())))
				&& ((this.getReceiveCompany() == castOther.getReceiveCompany())
						|| (this.getReceiveCompany() != null && castOther.getReceiveCompany() != null
								&& this.getReceiveCompany().equals(castOther.getReceiveCompany())))
				&& ((this.getReceiveMaterial() == castOther.getReceiveMaterial())
						|| (this.getReceiveMaterial() != null && castOther.getReceiveMaterial() != null
								&& this.getReceiveMaterial().equals(castOther.getReceiveMaterial())))
				&& ((this.getReceiveDate() == castOther.getReceiveDate())
						|| (this.getReceiveDate() != null && castOther.getReceiveDate() != null
								&& this.getReceiveDate().equals(castOther.getReceiveDate())))
				&& ((this.getReceiveAmount() == castOther.getReceiveAmount())
						|| (this.getReceiveAmount() != null && castOther.getReceiveAmount() != null
								&& this.getReceiveAmount().equals(castOther.getReceiveAmount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getReceiveId() == null ? 0 : this.getReceiveId().hashCode());
		result = 37 * result + (getReceiveCompany() == null ? 0 : this.getReceiveCompany().hashCode());
		result = 37 * result + (getReceiveMaterial() == null ? 0 : this.getReceiveMaterial().hashCode());
		result = 37 * result + (getReceiveDate() == null ? 0 : this.getReceiveDate().hashCode());
		result = 37 * result + (getReceiveAmount() == null ? 0 : this.getReceiveAmount().hashCode());
		return result;
	}

}
