package com.ybtx.domain;
// Generated 2017-7-28 23:24:18 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Submit generated by hbm2java
 */
public class Submit implements java.io.Serializable {

	private int submitId;
	private Company company;
	private Product product;
	private Serializable submitDate;
	private int submitAmount;

	public Submit() {
	}

	public Submit(int submitId, Company company, Product product, Serializable submitDate, int submitAmount) {
		this.submitId = submitId;
		this.company = company;
		this.product = product;
		this.submitDate = submitDate;
		this.submitAmount = submitAmount;
	}

	public int getSubmitId() {
		return this.submitId;
	}

	public void setSubmitId(int submitId) {
		this.submitId = submitId;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Serializable getSubmitDate() {
		return this.submitDate;
	}

	public void setSubmitDate(Serializable submitDate) {
		this.submitDate = submitDate;
	}

	public int getSubmitAmount() {
		return this.submitAmount;
	}

	public void setSubmitAmount(int submitAmount) {
		this.submitAmount = submitAmount;
	}

}
